### ISSUE TITLE
Potential Issue with Stresses and Number of Bands

### ISSUE THREAD

**Issue by umbriquse** [JuliaMolSim/DFTK.jl#512] opened 2021-08-10 16:44 UTC
I'm not certain if it is intentional on producing a matrix of NaN's if the number of bands is too high for a given system, but here's a MWE of this behavior

```
using DFTK

a = 10
lattice = a / 2 * [[0 1 1.];
                   [1 0 1.];
                   [1 1 0.]]

elements = ElementPsp(:Si, psp = load_psp("hgh/lda/Si-q4"))
atoms = [
    elements => [
        [0.75000000,  0.75000000,  0.75000000],
        [0.50000000,  0.50000000,  0.50000000]
    ]
]

model = model_DFT(lattice, atoms, Xc([:lda_c_vwn]); temperature = temperature)
basis = PlaneWaveBasis(model; Ecut = 19, kgrid = [1,1,1])
self_consistent_field(basis; n_ep_extra = 8) |> compute_stresses |> display
self_consistent_field(basis; n_ep_extra = 7) |> compute_stresses |> display
```

**Comment by antoine-levitt** [comment] 2021-08-11 07:03
Definitely not intended, thanks a lot for the nice reproducer, will investigate!

**Comment by antoine-levitt** [comment] 2021-08-11 10:55
What's the value of `temperature`?

**Comment by antoine-levitt** [comment] 2021-08-11 10:57
Can't reproduce the bug.

**Comment by umbriquse** [comment] 2021-08-11 13:34
Sorry about that
```
using DFTK

a = 10
lattice = a / 2 * [[0 1 1.];
                   [1 0 1.];
                   [1 1 0.]]

elements = ElementPsp(:Si, psp = load_psp("hgh/lda/Si-q4"))
atoms = [
    elements => [
        [0.75000000,  0.75000000,  0.75000000],
        [0.50000000,  0.50000000,  0.50000000]
    ]
]

model = model_DFT(lattice, atoms, Xc([:lda_c_vwn]); temperature = 0.0006)
basis = PlaneWaveBasis(model; Ecut = 19, kgrid = [1,1,1])
self_consistent_field(basis; n_ep_extra = 8) |> compute_stresses |> display
self_consistent_field(basis; n_ep_extra = 7) |> compute_stresses |> display
```

**Comment by antoine-levitt** [comment] 2021-08-11 19:52
Thanks! I can reproduce. That's a pretty low temperature; when you add bands, you get higher energies, so what probably happens is that an occupation underflows (is so low it passes the bounds of regular floating point arithmetic). That's handled correctly by the usual code, but forwarddiff apparently doesn't like that. I see we already have a comment `    # ForwardDiff gets NaNs for large arguments so we help it along` in occupation_derivative, so probably we need to special-case the `occupation` function also. Ideally we could fix it in ForwardDiff... The minimal example looks like
```
julia> ForwardDiff.derivative(x->(1+exp(x)), 20000.0)
Inf
julia> ForwardDiff.derivative(x->1/(1+exp(x)), 20000.0)
NaN
```
Maybe ForwardDiff could be more clever here?

**Comment by antoine-levitt** [comment] 2021-08-12 11:34
Should be fixed by https://github.com/JuliaMolSim/DFTK.jl/pull/513. Thanks for reporting!

**Closed** 2021-08-12 13:41 UTC
