### ISSUE TITLE
How to verify a PlaneWaveBasis has been updated?

### ISSUE THREAD

**Issue by umbriquse** [JuliaMolSim/DFTK.jl#445] opened 2021-06-08 19:38 UTC
I wrote a function that can update fields for the PlaneWaveBasis. In the process for writing a test for the function I've come across the issue of determining if two FFT plans are equivalent. 

As of:
```
  Status `~/git/Dino.jl/Project.toml`
  [acf6eb54] DFTK v0.3.1
```

```
using DFTK

# From what I understand the model and basis are arbitrary. My choices here were for convience
model = model_LDA(10.0 * [1 0 0; 0 1 0; 0 0 1], [ElementPsp(:O; psp = load_psp(list_psp(:O)[1].identifier)) => [zeros(3)]])
basis = PlaneWaveBasis(model, 10)
basis == deepcopy(basis)
```
`returns false`

I'm curious how to test if two FFT plans are equivalent, or if it's possible.

**Comment by antoine-levitt** [comment] 2021-06-08 20:04
As far as I know FFT plans contain pointers to the C library. But they do have a text representation that you can probably use to compare plans. Why do you need this?

**Comment by umbriquse** [comment] 2021-06-08 20:10
Just to confirm that if a field in the PlaneWaveBasis has been updated it would have the same FFT plans as if a new basis was created with the desired inputs.

**Comment by antoine-levitt** [comment] 2021-06-09 04:45
No, these structs (marked as struct and not mutable struct) are not mutable by design. Once a pwbasis is constructed it should not be changed. If you want to change it, create a new one.

**Comment by mfherbst** [comment] 2021-06-09 08:17
Sounds like this is answered. Feel free to reopen @umbriquse  if not.

**Closed by mfherbst** 2021-06-09 08:17 UTC
Labels: usage
