### ISSUE TITLE
Direct minimization with Double64 does not work

### ISSUE THREAD

**Issue by gkemlin** [JuliaMolSim/DFTK.jl#428] opened 2021-04-30 10:04 UTC
Hi there :)

I just encountered some bug when trying to use directminimization with Double64 precision. 

Here is the code I ran

```
using PyPlot
using DFTK
using DoubleFloats
using GenericLinearAlgebra

pot(G) = G == 0 ? zero(G) : 1 / abs(G)

a = 10
lattice = a * [[1 0 0.]; [0 0 0]; [0 0 0]]

C = 1
α = 2

n_electrons = 1  # Increase this for fun
terms = [Kinetic(),
         ExternalFromFourier(G -> pot(G[1])),
]
model = Model(Array{Double64}(lattice); n_electrons=n_electrons, terms=terms,
              spin_polarization=:spinless)

Ecut = 150
basis = PlaneWaveBasis(model, Ecut, kgrid=(1, 1, 1))
scfres = direct_minimization(basis, tol=1e-14)
scfres.energies

```

Here is the error raised

```
Iter     Function value   Gradient norm 
     0     5.880437e+01     6.495031e+01
 * time: 0.0010058879852294922
ERROR: LoadError: InexactError: DoubleFloat(NaN - NaN*im)
Stacktrace:
  [1] Real
    @ ./complex.jl:37 [inlined]
  [2] convert
    @ ./number.jl:7 [inlined]
  [3] setindex!
    @ ./array.jl:839 [inlined]
  [4] update_h!(d::NLSolversBase.OnceDifferentiable{Double64, Vector{Complex{Double64}}, Vector{Complex{Double64}}}, state::Optim.LBFGSState{Vector{Complex{Double64}}, Vector{Vector{Complex{Double64}}}, Vector{Vector{Complex{Double64}}}, Double64, Vector{Complex{Double64}}}, method::Optim.LBFGS{DFTK.DMPreconditioner, LineSearches.InitialStatic{Float64}, LineSearches.BackTracking{Float64, Int64}, typeof(DFTK.precondprep!)})
    @ Optim ~/.julia/packages/Optim/D7azp/src/multivariate/solvers/first_order/l_bfgs.jl:230
  [5] optimize(d::NLSolversBase.OnceDifferentiable{Double64, Vector{Complex{Double64}}, Vector{Complex{Double64}}}, initial_x::Vector{Complex{Double64}}, method::Optim.LBFGS{DFTK.DMPreconditioner, LineSearches.InitialStatic{Float64}, LineSearches.BackTracking{Float64, Int64}, typeof(DFTK.precondprep!)}, options::Optim.Options{Float64, Nothing}, state::Optim.LBFGSState{Vector{Complex{Double64}}, Vector{Vector{Complex{Double64}}}, Vector{Vector{Complex{Double64}}}, Double64, Vector{Complex{Double64}}})
    @ Optim ~/.julia/packages/Optim/D7azp/src/multivariate/optimize/optimize.jl:70
  [6] optimize
    @ ~/.julia/packages/Optim/D7azp/src/multivariate/optimize/optimize.jl:33 [inlined]
  [7] optimize(f::NLSolversBase.InplaceObjective{Nothing, DFTK.var"#fg!#522"{PlaneWaveBasis{Double64}, DFTK.var"#unpack#520"{Vector{Int64}, Vector{Int64}, Int64}, Vector{Vector{Double64}}, Int64, Int64}, Nothing, Nothing, Nothing}, initial_x::Vector{Complex{Double64}}, method::Optim.LBFGS{DFTK.DMPreconditioner, LineSearches.InitialStatic{Float64}, LineSearches.BackTracking{Float64, Int64}, typeof(DFTK.precondprep!)}, options::Optim.Options{Float64, Nothing}; inplace::Bool, autodiff::Symbol)
    @ Optim ~/.julia/packages/Optim/D7azp/src/multivariate/optimize/interface.jl:142
  [8] optimize(f::NLSolversBase.InplaceObjective{Nothing, DFTK.var"#fg!#522"{PlaneWaveBasis{Double64}, DFTK.var"#unpack#520"{Vector{Int64}, Vector{Int64}, Int64}, Vector{Vector{Double64}}, Int64, Int64}, Nothing, Nothing, Nothing}, initial_x::Vector{Complex{Double64}}, method::Optim.LBFGS{DFTK.DMPreconditioner, LineSearches.InitialStatic{Float64}, LineSearches.BackTracking{Float64, Int64}, typeof(DFTK.precondprep!)}, options::Optim.Options{Float64, Nothing})
    @ Optim ~/.julia/packages/Optim/D7azp/src/multivariate/optimize/interface.jl:141
  [9] direct_minimization(basis::PlaneWaveBasis{Double64}, ψ0::Nothing; prec_type::Type{PreconditionerTPA}, optim_solver::Type, tol::Float64, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ DFTK ~/Documents/Nextcloud/CERMICS/codes/DFTK/DFTK.jl/src/scf/direct_minimization.jl:135
 [10] #direct_minimization#508
    @ ~/Documents/Nextcloud/CERMICS/codes/DFTK/DFTK.jl/src/scf/direct_minimization.jl:68 [inlined]
 [11] top-level scope
    @ ~/Documents/Nextcloud/CERMICS/codes/DFTK/DFTK.jl/examples/gross_pitaevskii_analytic_linear.jl:28
 [12] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [13] top-level scope
    @ REPL[3]:1
in expression starting at /home/kemling/Documents/Nextcloud/CERMICS/codes/DFTK/DFTK.jl/examples/gross_pitaevskii_analytic_linear.jl:28
```

As replacing the direct minimization by the scf solver works (be careful to this bug https://github.com/JuliaMolSim/DFTK.jl/pull/427), I guess the problem is coming from the Optim.jl library compatibility with DoubleFloats.jl ?

**Comment by antoine-levitt** [comment] 2021-04-30 10:28
What's going on here is that in the line (l_bfgs:231)
```
    rho_iteration = one(eltype(state.dx)) / real(dot(state.dx, state.dg))
```
the dotproduct is NaN, so it goes into 1+0im / NaN => NaN-NaN im and then can't convert that to a real number. When the denominator is not NaN this works out fine. The problem of course is that the NaN should never been have there in the first place, so we should track the NaN and see where it comes from. It's weird because there's no issue in the float64 case.

**Comment by gkemlin** [comment] 2021-04-30 14:05
Yes, a few lines above, there is `state.dg .= gradient(d) .- state.g_previous` where this is `gradient(d)` which is NaN. Maybe it is linked to this issue https://github.com/JuliaNLSolvers/Optim.jl/issues/761 ? I will explore that.

**Comment by GVigne** [comment] 2022-03-27 14:39
I think I found the source of the problem, but I don't really know how to solve it. It comes from the `perform_linesearch` routine from the Optim package, which is called when the L-BFGS algorithm is used (_l_bfgs:204_). More precisely, after line 59 in  _perform_linesearch_ (which reads `state.alpha, ϕalpha =method.linesearch!(d, state.x, state.s, state.alpha,state.x_ls, phi_0, dphi_0)`), `state.alpha` is NaN, which prevents the rest of the code from executing correctly.

This comes from the LineSearches package. Line 32 in _backtracking.jl_ reads `α_0 = min(α_0, min(alphamax, ls.maxstep / norm(s, Inf)))`. In our case, `alphamax` and `ls.maxstep` are Inf. However, `Inf/a` behaves differently according to the type of `a`:
- if `a` is a Float64, `Inf/a` yields Inf
- if `a` is a Double64, `Inf/a` yields NaN
Therefore, in our case, line 32 is equivalent to 
- `α_0 = min(α_0, Inf)`, which gives Inf, in the Float64 case
- `α_0 = min(α_0, NaN)`, which gives NaN in the Double64 case.

The problem comes only from this line: wrapping it up in a if statement (to only do this line if `ls.maxstep` is not Inf) will make the entire code work just like the Float64 case (and will give the same energies).

It seems that it is just a matter of convention in the definition of `Inf/a`, so I can't really think of a pretty workaround without hardcoding that `ls.maxstep`  should not be Inf in the Double64 case.

**Comment by antoine-levitt** [comment] 2022-03-27 16:30
Hm, it's weird that Inf/a is Nan with double64, I would have expected it to follow standard IEEE floating point rules. If this is indeed the case it should be fixed in doublefloats. What is a here?

**Comment by antoine-levitt** [comment] 2022-03-27 16:37
Hm yeah looking at the doublefloats issue tracker there are a bunch of fixed bugs involving Inf and nans, looks like this is one of these. Can you open an issue there?

**Comment by GVigne** [comment] 2022-03-27 16:50
Here, `a` is ` norm(s, Inf)`  (and if I am not mistaken, it is not Inf, so the problem is not because of the operation ` Inf/Inf` ). And ` s`  is simply ` state.s` , where `state` is a `LBFGSState` object generated by the solver from a given inital state `(ψ0` here).
Yes, I will open an issue and see what can be done.

**Comment by antoine-levitt** [comment] 2022-03-27 17:04
This works though:
```
julia> Double64(Inf) / Double64(2.0)
Inf
```

**Comment by antoine-levitt** [comment] 2022-03-27 17:05
Although
```
julia> Inf / Double64(2.0)
NaN
```

**Comment by GVigne** [comment] 2022-03-27 18:55
Yes, it seems that it is a conflict between Inf when it is considered as a Float64 and the denominator `a` when it is a Double64, although there is no problem when doing operations using only Double64. Quite tricky!
Also, the problem only occurs when the denominator is a Double64 and the numerator is Inf. For instance,
```julia
julia> Double64(2.0)/Float64(Inf)
0.0
julia> typeof(Double64(2.0)/Float64(Inf))
Double64 (alias for Double64)
```

**Comment by antoine-levitt** [comment] 2022-03-31 19:32
Cool, thanks for reporting upstream!

**Closed by antoine-levitt** 2022-03-31 19:32 UTC
Labels: bug, good first issue, hacktoberfest
