### ISSUE TITLE
Adding options for setting the charge and mass of the electrons

### ISSUE THREAD

**Issue by stur86** [JuliaMolSim/DFTK.jl#380] opened 2020-11-19 16:43 UTC
Continuation of a topic I raised in https://github.com/JuliaMolSim/DFTK.jl/issues/367. I'm interested in solving problems involving positrons or muons in a system, either negative or positive. It would be really useful for me and anyone else working on this sort of problems if there was a way to configure the mass and charge of the particles we perform DFT on (even leaving aside the XC functionals, since most problems involve only one positron/muon). I understand this can be done my simply writing custom potentials - could there be maybe some helper function/class that turns regular electronic potentials into custom ones? I'm willing to work on contributing it if there's agreement about this idea as a useful new feature.

**Comment by antoine-levitt** [comment] 2020-11-19 16:49
Most of our terms have scaling factors that you can use to tweak this. DFTK mostly works in terms of mathematical rather than physical abstractions. So specifying the model is specifying a list of energy terms. So essentially you write down the equations of your model, and then you tell DFTK what the terms are. That should fit what you need, no?

**Comment by stur86** [comment] 2020-11-19 16:51
It sounds so, my issue with that is just that I'm not sure how it works. I thought these terms were functions, so does that mean you need to e.g. wrap them in more functions to change the signs were needed? That was the sort of thing I was wondering if a 'helper' could do.

**Comment by antoine-levitt** [comment] 2020-11-19 16:56
Look at the gross-pitaevskii example in the docs for how the "build-your-own-model" thing is done. For instance you can also add a `Hartree(scaling_factor=-1)` and you'll get particles that attract each other instead of repelling (of course that doesn't make any sense, but it gives you an idea of what you can do)

**Comment by mfherbst** [comment] 2020-11-19 17:00
They are not exactly functions, more functors (so functions that you can configure). For example if you wanted to scale the Hartree term by `0.5`, you construct a term `Hartree(0.5)`, that you then pass to a `model_atomic` function as an extra term. One example which shows this is the [Gross-Pitaevskii](https://juliamolsim.github.io/DFTK.jl/stable/examples/gross_pitaevskii/) equation. Of course no-one can stop you to code some terms by yourself and provided that they have the required interface (see the src/terms subfolder in the source code and the [terms.jl](https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/terms/terms.jl) file in particular), they will just work.

If you need to modify the nuclei-electron interaction you can use a custom potential, like in [this example](https://juliamolsim.github.io/DFTK.jl/stable/examples/custom_potential/).

**Comment by antoine-levitt** [comment] 2021-07-06 14:47
@stur86 going to close this because it seems the issue is resolved? Feel free to reopen to discuss further.

**Closed by antoine-levitt** 2021-07-06 14:47 UTC
Labels: feature
