### ISSUE TITLE
Use of Measurements.jl in DFTK

### ISSUE THREAD

**Issue by umbriquse** [JuliaMolSim/DFTK.jl#417] opened 2021-03-09 22:01 UTC
I'm curious if it's possible to propagate the uncertainty in the DFT calcuations using the Measurements package and report such error estimates along with each energy and force calculations. Understandably, error involving cutoff energy, kgrid spacing, use of pseudopotentials, etc... cannot be directly calculated, but from what I understand the error that is produced by the iterative technique of calculating the self consistent field would be able to be calculated and propagated.

Measurements.jl is just a package that propagates error in calculations.

**Comment by antoine-levitt** [comment] 2021-03-10 08:07
Hi,

That's a good question. What sort of uncertainty are you thinking about? The short answer is that you can't (easily) measure the error along the solver iterations, because 1) that's technically complicated (eg it requires support for eigenproblems) 2) it would probably blow up pretty quickly anyway because iterative solvers are "unstable" by design. What you can relatively easily do however is compute the error in the residuals, which is all "direct" operations (matmuls, FFTs). To the extent that you trust (or prove) that a small residual corresponds to a small error, this gives uncertainty estimates. We did this in https://arxiv.org/abs/2004.13549, where we used interval arithmetic, I would imagine measurements is even simpler (and faster).

We were very careful in that work to estimate all the errors properly, but probably you can get by with something simpler if you just want an estimate: it's very much ongoing research work for us.

**Comment by mfherbst** [comment] 2021-03-10 11:49
> where we used interval arithmetic, I would imagine measurements is even simpler (and faster).

Careful here. These two things don't really do the same thing. Measurements is useful for propagating uncertainty from input to output, but interval arithmetic keeps track of numerical error, that's including the error "generated" by doing the operations from input to output themselves.

**Comment by antoine-levitt** [comment] 2021-03-10 11:57
Right, but measurements is basically dual numbers plus some fancy things on top, it's easier than interval arithmetic. But I guess there's a confusion between two things here: one is uncertainty in the data (eg atomic positions, lattice), and for this you basically need derivatives (eg forces, stresses and higher derivatives). The second is uncertainty in the computation process, and for this you need error control (plus interval arithmetic or some such if you want to bother with machine precision errors)

**Comment by mfherbst** [comment] 2021-03-10 13:28
indeed that was my point as well. These are two different things.

**Comment by antoine-levitt** [comment] 2021-03-31 08:14
That's not really an uncertainty. From an error control point of view we don't particularly care about what the iterative process to solve F(x) = 0 is: what we care about is how well the system was solved: ie what is F(x) (the residual). The more delicate question then is: if you know that F(x) is small, what is the corresponding error on x?

**Comment by mfherbst** [comment] 2021-06-08 08:23
I'm closing this as the discussion started to diverge in a different direction. Essentially Measurements.jl could be used with DFTK (same as IntervalArithmetic), but probably will not yield what one is after (in the sense of the sensitivity of the SCF result on the input parameters), which is a more involved question where more mathematical developments are still needed.

**Closed by mfherbst** 2021-06-08 08:23 UTC
